#pragma once

#define RESOLUTIONX 1920
#define RESOLUTIONY 1080

#define MAPCHIP_SIZE_HEIGHT (60)
#define MAPCHIP_SIZE_WIDTH (60)

#define MAPCHIP_NUM_HEIGHT 18
#define MAPCHIP_NUM_WIDTH  32

extern int MapChipDate[MAPCHIP_NUM_HEIGHT][MAPCHIP_NUM_WIDTH];